#
# copyright: Palace Resorts
# description: Archivo de configuracion de la lambda programs
# author: Edder Salim Rosado Lira - Tomas Fernando Cob Cime - Edgar Rene Rodriguez Medina
# creation: Date 8 de Abril del 2021
#
get-programs:
  handler: src/lambdas/programs/handler.getData
  name: ${self:service}-${self:provider.stage}-client-get-programs
  description: Método demo para pruebas de template.
  tags: ${self:custom.environment.LAMBDA_TAGS_LIST}
  events:
    - http:
        path: api/programs
        method: get
        cors: true

get-program-by-id:
  handler: src/lambdas/programs/handler.getDataById
  name: ${self:service}-${self:provider.stage}-client-get-program-by-id
  description: Método demo para pruebas de template.
  tags: ${self:custom.environment.LAMBDA_TAGS_LIST}
  events:
    - http:
        path: api/programs/{id}
        method: get
        cors: true
        request:
          parameters:
            paths:
              id: true
