#
# copyright: Palace Resorts
# description: Archivo de configuracion de la lambda programs
# author: Edder Salim Rosado Lira - Tomas Fernando Cob Cime - Edgar Rene Rodriguez Medina
# creation: Date 8 de Abril del 2021
#
functionTest:
  handler: ./src/lambdas/normalhttp/testFunction.handler
  name: ${self:service}-${self:provider.stage}-client-get-programs
  description: Metodo de prueba de esta seccion
  tags: ${self:custom.environment.LAMBDA_TAGS_LIST}
  events:
    - http:
        path: api/test
        method: post
        cors: true
