#
# copyright: Palace Resorts
# description: Archivo de configuracion de la lambda chargebacktypes
# author: Edder Salim Rosado Lira - Tomas Fernando Cob Cime - Edgar Rene Rodriguez Medina
# creation: Date 8 de Abril del 2021
#
get-chargebacktypes:
  handler: src/lambdas/chargebacktypes/handler.getData
  name: ${self:service}-${self:provider.stage}-client-get-chargebacktypes
  description: Método demo para pruebas de template.
  tags: ${self:custom.environment.LAMBDA_TAGS_LIST}
  events:
    - http:
        path: api/chargebacktypes
        method: get
        cors: true

get-chargebacktypes-by-id:
  handler: src/lambdas/chargebacktypes/handler.getDataById
  name: ${self:service}-${self:provider.stage}-client-get-chargebacktypes-by-id
  description: Método demo para pruebas de template.
  tags: ${self:custom.environment.LAMBDA_TAGS_LIST}
  events:
    - http:
        path: api/chargebacktypes/{id}
        method: get
        cors: true
        request:
          parameters:
            paths:
              id: true
